### ISSUE TITLE
Missing default configuration

### ISSUE THREAD

**Issue by Roman3349** [contributte/console-extra#22]
The default configuration is missing in the latest version `0.5.0`. 

**Error log**:
```
   E_NOTICE: Trying to get property 'generators' of non-object
   
   in src/DI/AdvancedCacheConsoleExtension.php(47) 
   in src/DI/ConsoleBridgesExtension.php(59) Contributte\Console\Extra\DI\AdvancedCacheConsoleExtension->loadConfiguration()
   in src/DI/Compiler.php(229) Contributte\Console\Extra\DI\ConsoleBridgesExtension->loadConfiguration()
   in src/DI/Compiler.php(204) Nette\DI\Compiler->processExtensions()
   in src/DI/ContainerLoader.php(119) Nette\DI\Compiler->compile()
   in src/DI/ContainerLoader.php(79) Nette\DI\ContainerLoader->generate()
   in src/DI/ContainerLoader.php(44) Nette\DI\ContainerLoader->loadFile()
   in src/Bootstrap/Configurator.php(242) Nette\DI\ContainerLoader->load()
   in src/Bootstrap/Configurator.php(221) Nette\Configurator->loadContainer()
   in iqrf-gateway-webapp/tests/bootstrap.php(41) Nette\Configurator->createContainer()
   in ServiceModule/Models/UnknownManagerTest.php(18) require()
```

**Used configuration:** https://gitlab.iqrf.org/open-source/iqrf-gateway-webapp/blob/f5a0f0d16237d40e3dc925331d287a4f93178c70/app/config/console.neon)

**Comment by mabar** [comment]
Did you somehow installed it with nette 2.4? Version 0.5 is compatible with nette 3.0 and have schema instead of default configuration array.

**Comment by Roman3349** [comment]
I use this with Nette 3 - see [composer.json](https://gitlab.iqrfsdk.org/open-source/iqrf-gateway-webapp/blob/master/composer.json).

When I register only one DI bridge (eg `console.cache: Contributte\Console\Extra\DI\CacheConsoleExtension`) it works fine. But when I register all DI bridges via `console.extra: Contributte\Console\Extra\DI\ConsoleBridgesExtension` "the default configuration" is empty.
