### ISSUE TITLE
ScriptPath issue

### ISSUE THREAD

**Issue by elcheco** [contributte/console-extra#24]
Hi,

I have latest versions of contributte/console (0.7.1) and contributte/console-extra (dev-master) and these extensions are producing ScriptPath error:
- console.latte
- console.router 

error message:

<img width="547" alt="Screenshot 2019-09-27 at 13 51 19" src="https://user-images.githubusercontent.com/1447985/65767390-0929f280-e12e-11e9-91d3-2afff0a5172a.png">

I checked the UrlScript file and printed also the variables: `$path` is having the value, but `$this->ScriptPath` is null.

In config file I have just:
```
console:
    url: v73.seyvillas.local
```

Am I missing something in the config or it's a bug?

**Comment by elcheco** [comment]
Well, originally it's line 109 in the UrlScript.php (don't get confused)
The 112 is after I put the dump commands 🤦‍♂

**Comment by f3l1x** [comment]
Yep, I've just run into the same issue. I blame Nette 3 for that, because in 2.4 it works fine.
If you're only on HTTPS, you can try `https://v73.seyvillas.local` or similar for HTTP.

**Comment by elcheco** [comment]
Maybe just specify that the Http protocol needs to be always set ;-)

**Comment by mabar** [comment]
Protocol is noted in contributte/console docs
