### ISSUE TITLE
contributte:cache:generate -g option not work

### ISSUE THREAD

**Issue by her-ur** [contributte/console-extra#29]
If i use command `php bin/console.php contributte:cache:generate -g di` i get: 
```
In CacheGenerateCommand.php line 63:
Cannot run undefined generator "di"
```
Configuration is still the same that works before updating.

I think that [here](https://github.com/contributte/console-extra/blob/0fdc8f284a8aef6af7c2d17d833d76e8aa59b5aa/src/DI/AdvancedCacheConsoleExtension.php#L55) should be `$generatorName` used as a key in array `$generatorDefinitions`. Is that correct or there is a better solution?

**Comment by mabar** [comment]
Yeah, that looks correct. Same thing applies to cleaners. Will you send a PR?

**Comment by her-ur** [comment]
Here: https://github.com/contributte/console-extra/pull/30

**Comment by f3l1x** [comment]
Closing due patch in #30. Thanks @her-ur.
