### ISSUE TITLE
LocalFilesystemCleaner vs RobotLoader 3.4.0

### ISSUE THREAD

**Issue by Gappa** [contributte/console-extra#39]
There is an incompatibility with RobotLoader 3.4.0 when trying to clear its cache. (It works fine with version 3.3.2 & below).

``` 
Fatal error: Uncaught RuntimeException: Unable to create file '{_path_to_web_}/app/../temp/cache/nette.robotLoader/e6d54b90b1f4c8e8141ba9a16d30e092.php.lock'. fopen({_path_to_web_}/app/../temp/cache/nette.robotLoader/e6d54b90b1f4c8e8141ba9a16d30e092.php.lock): failed to open stream: No such file or directory in {_path_to_web_}/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php:524

Stack trace:
#0 {_path_to_web_}/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php(506): Nette\Loaders\RobotLoader->acquireLock('/home/users/dev...', 2)
#1 {_path_to_web_}/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php(84): Nette\Loaders\RobotLoader->saveCache()
#2 [internal function]: Nette\Loaders\RobotLoader->__destruct()
#3 {main} thrown in {_path_to_web_}/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php on line 524 
```

I think this is the commit part that is the culprit:

- https://github.com/nette/robot-loader/commit/120c1bccf6b62e00d9f86dd1ecab2813ec1be43a#diff-7665ade9d4c667b3f9d2331d5eef3fd78e6cbd28d4bc10853046a9887253a93fR81-R88

I'm not really sure what can be done about that since saving the cache in `__destruct` is a feature.

**Comment by f3l1x** [comment]
Should be fixed in https://github.com/contributte/console-extra/commit/3dfafb270b3c8deccb60cbab57c18464a64c30dd

Try this:

```
bin/console nette:cache:purge --recreate
```

It will try to recreate purged folders.
